# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://seesea2024.github.io/
date_format: "ordinal"
title: 老实记
# subtitle: ""
description: "老实记"
keywords: Stone, shidongwa, shidonghua, 石东华
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shi Donghua
organization: seesea2024.github.io
organization_url: https://seesea2024.github.io
github_username: seesea2024
location: Shanghai, China
email: 10189795@qq.com
pub_wx: WX公众号：老实记

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
     href: /archives/
     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
# markdown: kramdown
markdown: GFM
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: seesea2024/seesea2024.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: shidongwa
    repo: blog-comments
    oauth:
        client_id: 2443c55823f977361bae
        client_secret: ace39b2327a62f955b408d4197ff75fc946c8613
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: shidongwa
    repo: blog-comments
    clientID: 2443c55823f977361bae
    clientSecret: ace39b2327a62f955b408d4197ff75fc946c8613
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 




